'use client';
import React,{useEffect,useState} from 'react';
import {readUsers,saveUsers,addAdminNotification} from '../../../app/utils/authStore';
import {addTxn,setAdminWallet} from '../../../app/utils/walletStore';
export default function AdminWalletManager(){
 const [target,setTarget]=useState(''); const [amount,setAmount]=useState(''); const [remark,setRemark]=useState(''); const [users,setUsers]=useState<any[]>([]); const [tx,setTx]=useState<any[]>([]);
 const load=()=>{setUsers(readUsers().filter((u:any)=>String(u.role).toUpperCase()!=='ADMIN')); try{setTx(JSON.parse(localStorage.getItem('wallet_transactions_db')||'[]').slice(0,30))}catch{setTx([])}};
 useEffect(()=>{load();window.addEventListener('users_updated',load);window.addEventListener('wallet_updated',load);return()=>{window.removeEventListener('users_updated',load);window.removeEventListener('wallet_updated',load)}},[]);
 const credit=(e:React.FormEvent)=>{e.preventDefault();const a=Number(amount);const us=readUsers();const q=us.find((u:any)=>String(u.id)===target||String(u.phone)===target||String(u.email).toLowerCase()===target.toLowerCase());if(!q)return alert('User not found.');if(!a||a<=0)return alert('Valid amount enter karein.');q.walletBalance=Number(q.walletBalance||0)+a;saveUsers(us);setAdminWallet(Number.MAX_SAFE_INTEGER);addTxn({userId:q.id,type:'CREDIT',amount:a,description:remark||'Admin manual wallet credit',reference:`ADMIN-${Date.now()}`});addAdminNotification({type:'WALLET_CREDIT',title:'Admin Wallet Credit',message:`₹${a.toFixed(2)} credited to ${q.name||q.email}`,userId:q.id,amount:a,status:'Read'});setTarget('');setAmount('');setRemark('');alert(`₹${a.toFixed(2)} ${q.name||q.email} ke wallet me add ho gaya.`)};
 return <div><h1 style={{fontSize:24,fontWeight:900,color:'#fff'}}>Wallet & Transaction Manager</h1><p style={{color:'#94a3b8',fontSize:13}}>Admin source balance unlimited hai. User wallet individual hai.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1.7fr',gap:25}}><div style={{background:'#0f172a',padding:25,borderRadius:16,border:'1px solid #1e293b'}}><h3 style={{color:'#38bdf8'}}>➕ Admin Wallet Credit</h3><form onSubmit={credit} style={{display:'flex',flexDirection:'column',gap:12}}><select value={target} onChange={e=>setTarget(e.target.value)} required style={{padding:12,background:'#0b132b',color:'#fff',border:'1px solid #334155',borderRadius:8}}><option value=''>Select user</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email} • {u.phone||u.id} • ₹{Number(u.walletBalance||0).toFixed(2)}</option>)}</select><input type='number' min='0.01' step='0.01' value={amount} onChange={e=>setAmount(e.target.value)} placeholder='Amount ₹' required style={{padding:12,background:'#0b132b',color:'#fff',border:'1px solid #334155',borderRadius:8}}/><input value={remark} onChange={e=>setRemark(e.target.value)} placeholder='Remark' style={{padding:12,background:'#0b132b',color:'#fff',border:'1px solid #334155',borderRadius:8}}/><button style={{padding:12,border:0,borderRadius:8,background:'#10b981',color:'#fff',fontWeight:800}}>Credit User Wallet 🚀</button></form></div><div style={{background:'#0f172a',padding:25,borderRadius:16,border:'1px solid #1e293b',overflowX:'auto'}}><h3 style={{color:'#fff'}}>Users & Wallets</h3><table style={{width:'100%',fontSize:12}}><thead><tr><th>Name</th><th>Mobile</th><th>Email</th><th>Wallet</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name||'-'}</td><td>{u.phone||'-'}</td><td>{u.email}</td><td>₹{Number(u.walletBalance||0).toFixed(2)}</td><td>{u.accountStatus||'Pending'}</td></tr>)}</tbody></table><h4 style={{color:'#94a3b8',marginTop:20}}>Recent Transactions</h4>{tx.map((x:any)=><div key={x.id} style={{padding:'8px 0',borderBottom:'1px solid #1e293b',color:'#cbd5e1'}}>₹{Number(x.amount||0).toFixed(2)} • {x.description||x.type}</div>)}</div></div></div>
}
