'use client';
import React,{useEffect,useState} from 'react';
import {readUsers,saveUsers,addAdminNotification,type PortalUser} from '../../app/utils/authStore';

export default function AdminUserManagement(){
 const [users,setUsers]=useState<PortalUser[]>([]); const [showModal,setShowModal]=useState(false);
 const [form,setForm]=useState({name:'',role:'Retailer',mobile:'',email:'',password:''});
 const load=()=>setUsers(readUsers());
 useEffect(()=>{load();window.addEventListener('users_updated',load);window.addEventListener('id_creation_updated',load);return()=>{window.removeEventListener('users_updated',load);window.removeEventListener('id_creation_updated',load)}},[]);
 const approve=(id:string)=>{const now=new Date().toISOString(); const next=users.map(u=>String(u.id)===String(id)?{...u,accountStatus:'Active',paymentStatus:'Verified',activatedAt:now,approvedAt:now,approvedBy:'ADMIN'}:u); saveUsers(next);
   try{const reqs=JSON.parse(localStorage.getItem('id_creation_requests_db')||'[]');localStorage.setItem('id_creation_requests_db',JSON.stringify((Array.isArray(reqs)?reqs:[]).map((r:any)=>String(r.userId)===String(id)?{...r,accountStatus:'Active',paymentStatus:'Verified',status:'Approved',approvedAt:now}:r)));}catch{}
   alert('Payment verified. User ID ACTIVE kar di gayi hai.'); };
 const reject=(id:string)=>{const next=users.map(u=>String(u.id)===String(id)?{...u,accountStatus:'Rejected',paymentStatus:'Rejected'}:u);saveUsers(next);};
 const del=(id:string)=>{if(confirm('Delete this user?'))saveUsers(users.filter(u=>String(u.id)!==String(id)))};
 const create=(e:React.FormEvent)=>{e.preventDefault(); if(!form.name||!form.mobile||!form.email||!form.password)return alert('Name, Mobile, Gmail aur Password required hai.'); const u:PortalUser={id:`admin-${Date.now()}`,name:form.name.trim(),role:form.role.toLowerCase().replace(/ /g,'_'),phone:form.mobile.trim(),email:form.email.trim(),password:form.password,walletBalance:0,accountStatus:'Pending',paymentStatus:'Pending',createdAt:new Date().toISOString()}; saveUsers([u,...users]); addAdminNotification({type:'ID_CREATION',title:'New User Created by Admin',message:`${u.name} ki ID pending verification me create hui.`,userId:u.id,applicantName:u.name,mobile:u.phone,email:u.email,status:'Unread'}); setForm({name:'',role:'Retailer',mobile:'',email:'',password:''});setShowModal(false);};
 return <div>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:25}}><div><h1 style={{fontSize:24,fontWeight:900,color:'#fff'}}>User Management</h1><p style={{color:'#94a3b8'}}>New IDs DEACTIVE rahengi jab tak payment verify karke activate na ki jaye.</p></div><button onClick={()=>setShowModal(true)} style={{background:'#2563eb',color:'#fff',border:0,padding:'10px 18px',borderRadius:8,fontWeight:'bold'}}>+ Create User</button></div>
  <div style={{background:'#0f172a',border:'1px solid #1e293b',borderRadius:12,overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',textAlign:'left',fontSize:13}}><thead><tr style={{background:'#1e293b',color:'#94a3b8'}}>{['Name','Role','Mobile','Gmail','UTR','Payment','Wallet','Account Status','Action'].map(x=><th key={x} style={{padding:12}}>{x}</th>)}</tr></thead><tbody>
   {users.map(u=><tr key={u.id} style={{borderBottom:'1px solid #1e293b'}}><td style={{padding:12,color:'#fff',fontWeight:700}}>{u.name||'—'}</td><td style={{padding:12,color:'#38bdf8'}}>{u.role}</td><td style={{padding:12,color:'#cbd5e1'}}>{u.phone||'—'}</td><td style={{padding:12,color:'#cbd5e1'}}>{u.email||'—'}</td><td style={{padding:12,color:'#fbbf24'}}>{u.utr||'—'}</td><td style={{padding:12,color:String(u.paymentStatus).toLowerCase()==='verified'?'#4ade80':'#fbbf24'}}>{String(u.paymentStatus||'Pending').toUpperCase()}</td><td style={{padding:12,color:'#4ade80',fontWeight:700}}>₹{Number(u.walletBalance||0).toFixed(2)}</td><td style={{padding:12}}><span style={{padding:'4px 9px',borderRadius:20,background:String(u.accountStatus).toLowerCase()==='active'?'rgba(74,222,128,.12)':'rgba(251,191,36,.12)',color:String(u.accountStatus).toLowerCase()==='active'?'#4ade80':'#fbbf24',fontWeight:800}}>{String(u.accountStatus||'Pending').toUpperCase()}</span></td><td style={{padding:12,display:'flex',gap:6}}>{String(u.accountStatus).toLowerCase()!=='active'&&<button onClick={()=>approve(u.id)} style={{background:'#10b981',color:'#fff',border:0,padding:'6px 9px',borderRadius:6,fontWeight:700}}>Verify & Activate</button>}{String(u.accountStatus).toLowerCase()==='pending'&&<button onClick={()=>reject(u.id)} style={{background:'#ef4444',color:'#fff',border:0,padding:'6px 9px',borderRadius:6}}>Reject</button>}<button onClick={()=>del(u.id)} style={{background:'#475569',color:'#fff',border:0,padding:'6px 9px',borderRadius:6}}>Delete</button></td></tr>)}
  </tbody></table>{users.length===0&&<div style={{padding:30,textAlign:'center',color:'#94a3b8'}}>No users found.</div>}</div>
  {showModal&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.85)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000}}><form onSubmit={create} style={{background:'#0b132b',padding:28,borderRadius:18,width:480,display:'grid',gap:12}}><h3 style={{color:'#38bdf8'}}>Create User — Wallet ₹0 / Pending</h3>{[['name','Full Name'],['mobile','Mobile'],['email','Gmail ID'],['password','Password']].map(([k,l])=><input key={k} required placeholder={l} type={k==='password'?'password':'text'} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} style={{padding:11,borderRadius:8,border:'1px solid #334155',background:'#0f172a',color:'#fff'}}/>)}<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} style={{padding:11,borderRadius:8,background:'#0f172a',color:'#fff'}}><option>Retailer</option><option>Distributor</option><option>Super Distributor</option><option>Master Distributor</option></select><div style={{display:'flex',gap:10}}><button type="submit" style={{flex:1,padding:11,background:'#10b981',color:'#fff',border:0,borderRadius:8,fontWeight:700}}>Create Pending ID</button><button type="button" onClick={()=>setShowModal(false)} style={{padding:11,background:'#334155',color:'#fff',border:0,borderRadius:8}}>Cancel</button></div></form></div>}
 </div>
}
