'use client';
import React,{useEffect,useState} from 'react';
import {readUsers,addAdminNotification} from '../../../utils/authStore';
import {setWallet,addTxn} from '../../../utils/walletStore';
export default function RetailerWalletLoadPage(){
 const [requests,setRequests]=useState<any[]>([]); const [users,setUsers]=useState<any[]>([]);
 const load=()=>{try{setRequests(JSON.parse(localStorage.getItem('wallet_requests_db')||'[]'))}catch{setRequests([])}setUsers(readUsers())};
 useEffect(()=>{load();window.addEventListener('wallet_updated',load);window.addEventListener('users_updated',load);return()=>{window.removeEventListener('wallet_updated',load);window.removeEventListener('users_updated',load)}},[]);
 const action=(r:any,status:'Approved'|'Rejected')=>{const all=JSON.parse(localStorage.getItem('wallet_requests_db')||'[]');const next=all.map((x:any)=>x.id===r.id?{...x,status,approvedAt:new Date().toISOString()}:x);localStorage.setItem('wallet_requests_db',JSON.stringify(next));if(status==='Approved'){const us=readUsers();const u=us.find(x=>String(x.id)===String(r.userId)||String(x.phone)===String(r.phone));if(u){u.walletBalance=Number(u.walletBalance||0)+Number(r.amount||0);localStorage.setItem('appUsers',JSON.stringify(us));addTxn({userId:u.id,type:'CREDIT',amount:Number(r.amount),description:'Admin approved wallet recharge',reference:r.utr||r.id});addAdminNotification({type:'WALLET_APPROVED',title:'Wallet Recharge Approved',message:`₹${Number(r.amount).toFixed(2)} added to ${u.name||u.email}`,userId:u.id,status:'Read'});}}window.dispatchEvent(new Event('wallet_updated'));alert(status==='Approved'?'Wallet credited successfully.':'Request rejected.');};
 return <div style={{padding:25,color:'#fff'}}><h1>Wallet Recharge Requests</h1><p style={{color:'#94a3b8'}}>UPI/UTR requests: admin approval ke baad user wallet credit hota hai. Admin source balance par koi limit/deduction nahi hai.</p>{requests.map(r=><div key={r.id} style={{background:'#0f172a',padding:18,borderRadius:12,margin:'10px 0',border:'1px solid #1e293b'}}><b>{r.user||r.retailerName}</b> • {r.phone||'-'} • {r.email||'-'}<div>Amount: ₹{Number(r.amount||0).toFixed(2)} • UTR: {r.utr||'-'} • Status: {r.status||'Pending'}</div>{(r.status||'Pending')==='Pending'&&<div style={{marginTop:10,display:'flex',gap:8}}><button onClick={()=>action(r,'Approved')} style={{background:'#10b981',color:'#fff',border:0,padding:'8px 14px',borderRadius:7}}>Approve & Credit</button><button onClick={()=>action(r,'Rejected')} style={{background:'#ef4444',color:'#fff',border:0,padding:'8px 14px',borderRadius:7}}>Reject</button></div>}</div>)}</div>
}
