import { NextResponse } from 'next/server';
const HOP=new Set(['connection','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding','upgrade','host','content-length']);
function base(){const raw=String(process.env.BACKEND_API_URL||process.env.NEXT_PUBLIC_API_BASE_URL||'').trim();if(!raw)return '';try{const url=new URL(raw);if(!['http:','https:'].includes(url.protocol))return '';const b=url.toString().replace(/\/$/,'');return b.endsWith('/api')?b:`${b}/api`;}catch{return '';}}
async function proxy(request:Request,path:string[]){const root=base();if(!root)return NextResponse.json({error:'Backend API is not configured on the live deployment.'},{status:503});try{const headers=new Headers();request.headers.forEach((v,k)=>{if(!HOP.has(k.toLowerCase()))headers.set(k,v);});const method=request.method.toUpperCase();const response=await fetch(`${root}/admin/${path.map(encodeURIComponent).join('/')}${new URL(request.url).search}`,{method,headers,body:['GET','HEAD'].includes(method)?undefined:await request.arrayBuffer(),cache:'no-store',redirect:'manual'});const out=new Headers();response.headers.forEach((v,k)=>{if(!HOP.has(k.toLowerCase()))out.set(k,v);});return new NextResponse(response.body,{status:response.status,statusText:response.statusText,headers:out});}catch(error:any){return NextResponse.json({error:'Backend API is unreachable.',detail:error?.message||'Unknown error'},{status:502});}}
export async function GET(r:Request,c:{params:Promise<{path:string[]}>}){return proxy(r,(await c.params).path||[])}
export async function POST(r:Request,c:{params:Promise<{path:string[]}>}){return proxy(r,(await c.params).path||[])}
export async function PUT(r:Request,c:{params:Promise<{path:string[]}>}){return proxy(r,(await c.params).path||[])}
export async function PATCH(r:Request,c:{params:Promise<{path:string[]}>}){return proxy(r,(await c.params).path||[])}
export async function DELETE(r:Request,c:{params:Promise<{path:string[]}>}){return proxy(r,(await c.params).path||[])}
